-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.
-- This is the ACTUAL production schema (all IDs are UUID, not bigint as previously documented)

CREATE TABLE public.user_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid UNIQUE,
  first_name text NOT NULL,
  last_name text NOT NULL,
  phone text,
  profile_photo_url text,
  role text NOT NULL CHECK (role = ANY (ARRAY['owner'::text, 'walker'::text, 'admin'::text])),
  is_profile_complete boolean DEFAULT false,
  date_of_birth date,
  gender text CHECK (gender = ANY (ARRAY['male'::text, 'female'::text, 'other'::text, 'prefer_not_to_say'::text])),
  notification_preferences jsonb DEFAULT '{"sms": false, "push": true, "email": true}'::jsonb,
  language text DEFAULT 'es'::text,
  timezone text DEFAULT 'America/Bogota'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  balance numeric NOT NULL DEFAULT 0,
  id_number text,
  address text,
  bio text,
  experience_years integer,
  has_own_dogs boolean DEFAULT false,
  bank_account_type text,
  bank_account_number text,
  bank_name text,
  lat double precision,
  lng double precision,
  age integer,
  push_token text,
  device_platform text,
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.pets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_id uuid,
  name text NOT NULL,
  breed text,
  age_years integer,
  age_months integer,
  weight_kg numeric,
  gender text CHECK (gender = ANY (ARRAY['male'::text, 'female'::text])),
  size text CHECK (size = ANY (ARRAY['small'::text, 'medium'::text, 'large'::text, 'giant'::text])),
  is_neutered boolean DEFAULT false,
  energy_level text CHECK (energy_level = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text])),
  special_needs text,
  behavioral_notes text,
  medical_conditions text,
  allergies text,
  vet_info jsonb DEFAULT '{}'::jsonb,
  favorite_activities ARRAY,
  fears ARRAY,
  photos jsonb DEFAULT '[]'::jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT pets_pkey PRIMARY KEY (id),
  CONSTRAINT pets_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title text NOT NULL,
  body text,
  link_to text,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.walkers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text,
  location text,
  rating numeric,
  reviews integer,
  price numeric,
  img text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  user_id uuid UNIQUE,
  service_latitude double precision,
  service_longitude double precision,
  service_radius_km integer,
  is_verified boolean DEFAULT false,
  verification_status text DEFAULT 'pending'::text CHECK (verification_status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  id_document_front text,
  id_document_back text,
  criminal_record_cert text,
  selfie_with_id text,
  id_verification_status text DEFAULT 'pending'::text,
  background_check_status text DEFAULT 'pending'::text,
  overall_verification_status text DEFAULT 'pending'::text,
  verified_by_admin_id uuid,
  verified_at timestamp with time zone,
  rejection_reason text,
  verification_notes text,
  bank_account_verified boolean DEFAULT false,
  bank_verification_doc text,
  bio text,
  is_online boolean NOT NULL DEFAULT true,
  CONSTRAINT walkers_pkey PRIMARY KEY (id),
  CONSTRAINT fk_walkers_user_profiles FOREIGN KEY (user_id) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.bookings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  address text,
  duration text,
  total_price numeric,
  status text DEFAULT 'pending'::text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  lat double precision,
  lng double precision,
  scheduled_date text,
  scheduled_time text,
  rating integer,
  review_text text,
  walker_id uuid,
  service_type text DEFAULT 'regular_walk'::text CHECK (service_type = ANY (ARRAY['regular_walk'::text, 'extended_walk'::text, 'group_walk'::text, 'puppy_care'::text, 'elderly_care'::text, 'special_needs'::text])),
  special_instructions text,
  walker_notes text,
  owner_notes text,
  photos_taken jsonb DEFAULT '[]'::jsonb,
  walk_start_time timestamp with time zone,
  walk_end_time timestamp with time zone,
  actual_duration_minutes integer,
  route_data jsonb DEFAULT '{}'::jsonb,
  updated_at timestamp with time zone DEFAULT now(),
  pet_ids ARRAY,
  mercadopago_preference_id text,
  is_paid boolean DEFAULT false,
  payment_method text,
  payment_completed_at timestamp with time zone,
  CONSTRAINT bookings_pkey PRIMARY KEY (id),
  CONSTRAINT bookings_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT bookings_walker_id_fkey FOREIGN KEY (walker_id) REFERENCES public.walkers(id)
);
CREATE TABLE public.booking_reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid,
  reviewer_id uuid,
  reviewee_id uuid,
  rating integer CHECK (rating >= 1 AND rating <= 5),
  comment text,
  punctuality_rating integer CHECK (punctuality_rating >= 1 AND punctuality_rating <= 5),
  communication_rating integer CHECK (communication_rating >= 1 AND communication_rating <= 5),
  care_rating integer CHECK (care_rating >= 1 AND care_rating <= 5),
  overall_experience_rating integer CHECK (overall_experience_rating >= 1 AND overall_experience_rating <= 5),
  would_recommend boolean,
  public_response text,
  is_public boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT booking_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT booking_reviews_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT booking_reviews_reviewer_id_fkey FOREIGN KEY (reviewer_id) REFERENCES auth.users(id),
  CONSTRAINT booking_reviews_reviewee_id_fkey FOREIGN KEY (reviewee_id) REFERENCES auth.users(id)
);
CREATE TABLE public.conversations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  participant_one_id uuid,
  participant_two_id uuid,
  booking_id uuid,
  last_message_id uuid,
  last_message_at timestamp with time zone,
  participant_one_unread_count integer DEFAULT 0,
  participant_two_unread_count integer DEFAULT 0,
  is_archived_by_participant_one boolean DEFAULT false,
  is_archived_by_participant_two boolean DEFAULT false,
  is_blocked_by_participant_one boolean DEFAULT false,
  is_blocked_by_participant_two boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT conversations_pkey PRIMARY KEY (id),
  CONSTRAINT conversations_participant_one_id_fkey FOREIGN KEY (participant_one_id) REFERENCES auth.users(id),
  CONSTRAINT conversations_participant_two_id_fkey FOREIGN KEY (participant_two_id) REFERENCES auth.users(id),
  CONSTRAINT conversations_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid,
  sender_id uuid,
  receiver_id uuid,
  message_text text,
  message_type text DEFAULT 'text'::text CHECK (message_type = ANY (ARRAY['text'::text, 'image'::text, 'location'::text, 'file'::text, 'system_notification'::text])),
  media_url text,
  media_metadata jsonb DEFAULT '{}'::jsonb,
  location_data jsonb DEFAULT '{}'::jsonb,
  is_read boolean DEFAULT false,
  read_at timestamp with time zone,
  is_edited boolean DEFAULT false,
  edited_at timestamp with time zone,
  is_deleted boolean DEFAULT false,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id),
  CONSTRAINT messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES auth.users(id),
  CONSTRAINT messages_receiver_id_fkey FOREIGN KEY (receiver_id) REFERENCES auth.users(id)
);
CREATE TABLE public.locations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid,
  walker_id uuid,
  latitude numeric NOT NULL,
  longitude numeric NOT NULL,
  altitude numeric,
  accuracy numeric,
  speed numeric,
  heading numeric,
  activity_type text DEFAULT 'walking'::text CHECK (activity_type = ANY (ARRAY['stationary'::text, 'walking'::text, 'running'::text, 'driving'::text, 'cycling'::text])),
  timestamp timestamp with time zone NOT NULL,
  battery_level integer CHECK (battery_level >= 0 AND battery_level <= 100),
  signal_strength text CHECK (signal_strength = ANY (ARRAY['excellent'::text, 'good'::text, 'fair'::text, 'poor'::text, 'none'::text])),
  location_source text DEFAULT 'gps'::text CHECK (location_source = ANY (ARRAY['gps'::text, 'network'::text, 'passive'::text, 'manual'::text])),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT locations_pkey PRIMARY KEY (id),
  CONSTRAINT locations_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT locations_walker_id_fkey FOREIGN KEY (walker_id) REFERENCES public.walkers(id)
);
CREATE TABLE public.payouts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  walker_id uuid NOT NULL,
  amount numeric NOT NULL,
  status text NOT NULL DEFAULT 'completed'::text,
  payout_date date NOT NULL DEFAULT CURRENT_DATE,
  transaction_ids ARRAY,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payouts_pkey PRIMARY KEY (id),
  CONSTRAINT payouts_walker_id_fkey FOREIGN KEY (walker_id) REFERENCES public.walkers(id)
);
CREATE TABLE public.transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  transaction_number text NOT NULL DEFAULT ((('TX-'::text || to_char(now(), 'YYYYMMDD'::text)) || '-'::text) || lpad((floor((random() * (10000)::double precision)))::text, 4, '0'::text)) UNIQUE,
  user_id uuid,
  booking_id uuid,
  transaction_type text NOT NULL CHECK (transaction_type = ANY (ARRAY['payment'::text, 'refund'::text, 'deposit'::text, 'withdrawal'::text, 'penalty'::text, 'bonus'::text])),
  amount integer NOT NULL,
  fee_amount integer DEFAULT 0,
  net_amount integer,
  currency text DEFAULT 'COP'::text,
  payment_method text CHECK (payment_method = ANY (ARRAY['cash'::text, 'credit_card'::text, 'debit_card'::text, 'nequi'::text, 'davivienda'::text, 'pse'::text, 'wallet'::text])),
  payment_gateway text,
  gateway_transaction_id text,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text, 'cancelled'::text, 'refunded'::text])),
  description text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  platform_fee numeric,
  net_earning numeric,
  gateway_fee numeric DEFAULT 0,
  CONSTRAINT transactions_pkey PRIMARY KEY (id),
  CONSTRAINT transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT transactions_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id)
);
CREATE TABLE public.walker_availability (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  walker_id uuid NOT NULL,
  day_of_week smallint NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT walker_availability_pkey PRIMARY KEY (id),
  CONSTRAINT walker_availability_walker_id_fkey FOREIGN KEY (walker_id) REFERENCES public.walkers(id)
);
CREATE TABLE public.walker_certifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  walker_id uuid,
  certification_type text NOT NULL CHECK (certification_type = ANY (ARRAY['pet_first_aid'::text, 'dog_training'::text, 'professional_walker'::text, 'insurance'::text, 'background_check'::text])),
  certification_name text NOT NULL,
  issuing_organization text,
  certificate_number text,
  issue_date date,
  expiry_date date,
  certificate_url text,
  is_verified boolean DEFAULT false,
  verification_notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT walker_certifications_pkey PRIMARY KEY (id),
  CONSTRAINT walker_certifications_walker_id_fkey FOREIGN KEY (walker_id) REFERENCES public.walkers(id)
);
